export default [
  {
    ignores: [
      'node_modules/**',
      'vendor/**',
      'out/**',
      '.claude/**',
      'coverage/**',
      'test-results/**',
      'playwright-report/**',
    ],
  },
  {
    files: ['**/*.js'],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: {
        AbortController: 'readonly',
        Blob: 'readonly',
        Buffer: 'readonly',
        DOMException: 'readonly',
        Event: 'readonly',
        Float32Array: 'readonly',
        Float64Array: 'readonly',
        ImageData: 'readonly',
        Int32Array: 'readonly',
        Int8Array: 'readonly',
        L: 'readonly',
        Map: 'readonly',
        OffscreenCanvas: 'readonly',
        Promise: 'readonly',
        Set: 'readonly',
        URL: 'readonly',
        Uint8Array: 'readonly',
        Uint8ClampedArray: 'readonly',
        WebSocket: 'readonly',
        clearTimeout: 'readonly',
        console: 'readonly',
        createImageBitmap: 'readonly',
        document: 'readonly',
        fetch: 'readonly',
        localStorage: 'readonly',
        navigator: 'readonly',
        performance: 'readonly',
        setTimeout: 'readonly',
        window: 'readonly',
      },
    },
    rules: {
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }],
      'no-undef': 'off',
    },
  },
  {
    files: ['main.js', 'preload.js', 'src/main/**/*.js'],
    languageOptions: {
      sourceType: 'commonjs',
      globals: {
        __dirname: 'readonly',
        Buffer: 'readonly',
        console: 'readonly',
        module: 'readonly',
        process: 'readonly',
        require: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
      },
    },
  },
];
